# Generated by Django 5.0.10 on 2026-02-05 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='entity_type',
            field=models.CharField(choices=[('task', 'Task'), ('event', 'Event'), ('project', 'Project')], max_length=32),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('due_soon', 'Due Soon'), ('event_soon', 'Event Soon'), ('join_request', 'Join Request')], max_length=32),
        ),
    ]
