# Generated by Django 5.0.10 on 2026-02-05 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_entity_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='entity_type',
            field=models.CharField(choices=[('task', 'Task'), ('event', 'Event'), ('project', 'Project'), ('project_member', 'Project Member')], max_length=32),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('due_soon', 'Due Soon'), ('event_soon', 'Event Soon'), ('join_request', 'Join Request'), ('project_join_approved', 'Project Join Approved'), ('project_join_rejected', 'Project Join Rejected')], max_length=32),
        ),
    ]
