# Generated by Django 5.0.10 on 2026-01-30 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_add_profile_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='preferred_language',
            field=models.CharField(choices=[('ja', 'Japanese'), ('uz', 'Uzbek')], default='ja', max_length=2),
        ),
    ]
