# Generated by Django 5.0.10 on 2026-01-30 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='project',
        ),
        migrations.AddField(
            model_name='task',
            name='projects',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='projects.project'),
        ),
    ]
